version: "3.9"

services:

  db:
    image: gvenzl/oracle-xe:18-slim
    container_name: db_oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
      APP_USER: useroracle
      APP_USER_PASSWORD: 123456
    volumes:
      - oracle-volume-db:/opt/oracle/oradata
    networks:
      - default

  backend:
    container_name: backend
    build:
      context: back-end-quarkus
      dockerfile: Dockerfiledev
    ports:
      - "8080:8080"
      - "5005:5005"
    working_dir: /back-end-quarkus
    volumes:
      - ./back-end-quarkus:/back-end-quarkus
      - cache_gradle:/home/appuser/.gradle

    networks:
      - default
    depends_on:
      - db
      - frontend
    entrypoint: ./gradlew quarkusDev -Dquarkus.http.host=0.0.0.0
    #entrypoint: ./gradlew quarkusDev -DdebugHost=0.0.0.0


  frontend:
    container_name: frontend
    build:
      context: front-end-nextjs
      dockerfile: Dockerfiledev
    ports:
      - "3000:3000"
    working_dir: /front-end-nextjs
    volumes:
      - ./front-end-nextjs:/front-end-nextjs
      - /front-end-nextjs/node_modules
      - /front-end-nextjs/.next
    networks:
      - default
    depends_on:
      - db
    entrypoint: yarn dev




volumes:
  oracle-volume-db:
  cache_gradle:
    driver: local

networks:
  default:
    driver: bridge
